### ISSUE TITLE
issue deploying in vercel (nextjs)

### ISSUE THREAD

**Issue by erwinagpasa** [msaracevic/react-embed-gist#10]
[10:38:43.857] Running build in San Francisco, USA (West) – sfo1
[10:38:43.912] Cloning github.com/erwinagpasa/blogmail.io (Branch: main, Commit: 58f497e)
[10:38:44.987] Cloning completed: 1.073s
[10:38:46.979] Restored build cache
[10:38:47.027] Running "vercel build"
[10:38:47.706] Vercel CLI 31.0.4
[10:38:48.049] Installing dependencies...
[10:38:49.408] 
[10:38:49.409] up to date in 858ms
[10:38:49.409] 
[10:38:49.409] 129 packages are looking for funding
[10:38:49.410]   run `npm fund` for details
[10:38:49.421] Detected Next.js version: 13.4.9
[10:38:49.424] Detected `package-lock.json` generated by npm 7+...
[10:38:49.425] Running "npm run build"
[10:38:49.828] 
[10:38:49.828] > blogmail.io@0.1.0 build
[10:38:49.828] > next build
[10:38:49.828] 
[10:38:50.548] - info Creating an optimized production build...
[10:39:02.978] - info Compiled successfully
[10:39:02.980] - info Linting and checking validity of types...
[10:39:06.627] - info Collecting page data...
[10:39:07.466] - info Generating static pages (0/5)
[10:39:07.560] - info Generating static pages (1/5)
[10:39:07.660] - info Generating static pages (2/5)
[10:39:07.760] - info Generating static pages (3/5)
[10:39:07.764] ReferenceError: self is not defined
[10:39:07.765]     at 7900 (/vercel/path0/.next/server/chunks/786.js:883:63)
[10:39:07.765]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[10:39:07.765]     at 6207 (/vercel/path0/.next/server/app/page.js:307:74)
[10:39:07.766]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[10:39:07.766]     at M (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:24:46)
[10:39:07.766]     at ia (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:21:89)
[10:39:07.767]     at Ue (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:118:497)
[10:39:07.768]     at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
[10:39:07.772]     at Ve (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:155)
[10:39:07.772]     at Xe (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:122:289)
[10:39:07.804] 
[10:39:07.805] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[10:39:07.805] ReferenceError: self is not defined
[10:39:07.805]     at 7900 (/vercel/path0/.next/server/chunks/786.js:883:63)
[10:39:07.805]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[10:39:07.805]     at 6207 (/vercel/path0/.next/server/app/page.js:307:74)
[10:39:07.805]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[10:39:07.806]     at M (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:24:46)
[10:39:07.806]     at ia (/vercel/path0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:21:89)
[10:39:07.806]     at Ue (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:118:497)
[10:39:07.806]     at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
[10:39:07.806]     at Ve (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:155)
[10:39:07.806]     at Xe (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:122:289)
[10:39:07.917] - info Generating static pages (5/5)
[10:39:07.919] 
[10:39:07.920] > Export encountered errors on following paths:
[10:39:07.920] 	/page: /
[10:39:07.960] Error: Command "npm run build" exited with 1

<img width="1351" alt="Screenshot 2023-07-22 at 10 47 18 AM" src="https://github.com/msaracevic/react-embed-gist/assets/637956/f6146d30-b84b-464a-9e25-0097acc500d1">

**Comment by msaracevic** [comment]
Sorry, I am failing to understand how this error is related to this package?

**Comment by msaracevic** [comment]
Closing due to no context or follow up...
